#pragma once

#define ENGINE_VERSION "0.0.1 alpha"

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define WINDOW_WIDTH_EDITOR_MODE 1280
#define WINDOW_HEIGHT_EDITOR_MODE 720
#define WINDOW_NAME "game"
#define RENDERER_QUEUE_LAYERS 10
#define RENDERER_QUEUE_LAYER_SIZE 100

#define FULLSCREEN_DEFAULT 0
#define RENDERER_ACCELERATED
#define VSYNC true
#define FPS 60
#define VIDEO_ADAPTER_INDEX -1
#define RENDERER_OPENGL_MODE true

#define MAX_CHANNELS 16
